## Week 1 Discussion Section: Prey species in the California drylands
What is this data about? This dataset contains occurrence records and associated climate and environmental data for all arthropod prey of listed species in California drylands.  

Is this data collected in situ by the authors or is it a synthesis of multiple datasets? This data is a synthesis of multiple datasets. 

During what time frame were the observations in the dataset collected? Collection of this data began in 1945 and ended in 2022.

Does this dataset come with an associated metadata file? This dataset comes with an associated metadata file. 

Does the dataset contain sensitive data? This dataset does not contain sensitive data. 

*Citation:* Rachel King, Jenna Braun, Michael Westphal, & CJ Lortie. (2023). Compiled occurrence records for prey items of listed species found in California drylands with associated environmental data. Knowledge Network for Biocomplexity. doi:10.5063/F1VM49RH.
*Date of Access:* 10/1/2026
*Link:* https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1VM49RH

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e')
df.head()

  attribute                            description
0     class   taxonomic class of observed organism
1     order   taxonomic order of observed organism
2    family  taxonomic family of observed organism
3     genus                             genus name
4   species               full latin binomial name

In [3]:
# Load data
prey = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A23d42528-1048-45d4-85d1-7e13b666e744')
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

What do you notice in the columns section? 

There is a break in the columns and not all columns are shown.

In [7]:
# Below code changes default setting so that all columns are displayed
pd.set_option("display.max_columns", None)

# Now when you call `prey` data frame, all the columns are visible
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

**Step 5: pd.DataFrame preliminary exploration**

In [8]:
# head()
# returns the first five rows of the data frame
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

In [9]:
# tail()
# returns the last five rows of the data frame
prey.tail()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [10]:
# nunique()
# gives the number of unique values in each column
prey.nunique()

class                                 4
order                                18
family                               63
genus                                92
species                              97
lat                               91909
long                              91965
eventDate                        102140
day                                  31
month                                12
year                                 77
institutionCode                      77
coordinateUncertaintyInMeters      4450
basisOfRecord                         4
individualCount                      42
datasetKey                           88
ID                               111156
bio1                              11778
bio10                             11981
bio11                             11803
bio12                             12117
bio13                             12020
bio14                              4586
bio15                             11848
bio16                             12102
bio17                              9243
bio18                             10698
bio19                             12095
bio2                              11915
bio3                               8723
bio4                              12110
bio5                              11992
bio6                              11934
bio7                              12088
bio8                              11889
bio9                              11980
dist                              11718
dem90_hf                          11904
lc_class                             12
ndvi                              29093
dtype: int64

In [11]:
# info()
# tells us data type and how many rows we actually have a value for that column (aka how many of them do not have NA values)
# lists the column names in order
prey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111156 entries, 0 to 111155
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   class                          111156 non-null  object
 1   order                          111054 non-null  object
 2   family                         111156 non-null  object
 3   genus                          111156 non-null  object
 4   species                        111156 non-null  object
 5   lat                            111156 non-null  float64
 6   long                           111156 non-null  float64
 7   eventDate                      111156 non-null  object
 8   day                            110998 non-null  float64
 9   month                          111127 non-null  float64
 10  year                           111156 non-null  int64
 11  institutionCode                110414 non-null  object
 12  coordinateUncertaintyInMeters  84686 non-null   float64
 13  basisOfRecord                  111156 non-null  object
 14  individualCount                6351 non-null    float64
 15  datasetKey                     111156 non-null  object
 16  ID                             111156 non-null  int64
 17  bio1                           109629 non-null  float64
 18  bio10                          109629 non-null  float64
 19  bio11                          109629 non-null  float64
 20  bio12                          109629 non-null  float64
 21  bio13                          109629 non-null  float64
 22  bio14                          109629 non-null  float64
 23  bio15                          109629 non-null  float64
 24  bio16                          109629 non-null  float64
 25  bio17                          109629 non-null  float64
 26  bio18                          109629 non-null  float64
 27  bio19                          109629 non-null  float64
 28  bio2                           109629 non-null  float64
 29  bio3                           109629 non-null  float64
 30  bio4                           109629 non-null  float64
 31  bio5                           109629 non-null  float64
 32  bio6                           109629 non-null  float64
 33  bio7                           109629 non-null  float64
 34  bio8                           109629 non-null  float64
 35  bio9                           109629 non-null  float64
 36  dist                           109500 non-null  float64
 37  dem90_hf                       107765 non-null  float64
 38  lc_class                       106905 non-null  object
 39  ndvi                           109663 non-null  float64
dtypes: float64(28), int64(2), object(10)
memory usage: 33.9+ MB

In [12]:
# .shape
# gives us (number of rows, number of columns)
prey.shape

(111156, 40)

In [13]:
# .columns
# gives an index of all column names in the dataset

prey.columns

Index(['class', 'order', 'family', 'genus', 'species', 'lat', 'long',
       'eventDate', 'day', 'month', 'year', 'institutionCode',
       'coordinateUncertaintyInMeters', 'basisOfRecord', 'individualCount',
       'datasetKey', 'ID', 'bio1', 'bio10', 'bio11', 'bio12', 'bio13', 'bio14',
       'bio15', 'bio16', 'bio17', 'bio18', 'bio19', 'bio2', 'bio3', 'bio4',
       'bio5', 'bio6', 'bio7', 'bio8', 'bio9', 'dist', 'dem90_hf', 'lc_class',
       'ndvi'],
      dtype='object')

In [14]:
# .dtypes
# displays what type of data in each column
prey.dtypes

class                             object
order                             object
family                            object
genus                             object
species                           object
lat                              float64
long                             float64
eventDate                         object
day                              float64
month                            float64
year                               int64
institutionCode                   object
coordinateUncertaintyInMeters    float64
basisOfRecord                     object
individualCount                  float64
datasetKey                        object
ID                                 int64
bio1                             float64
bio10                            float64
bio11                            float64
bio12                            float64
bio13                            float64
bio14                            float64
bio15                            float64
bio16                            float64
bio17                            float64
bio18                            float64
bio19                            float64
bio2                             float64
bio3                             float64
bio4                             float64
bio5                             float64
bio6                             float64
bio7                             float64
bio8                             float64
bio9                             float64
dist                             float64
dem90_hf                         float64
lc_class                          object
ndvi                             float64
dtype: object

**Step 6: Update column names**

In [17]:
# Update the institutionCode and datasetKey columns with new names
prey = prey.rename(columns={"institutionCode":"institution_code", "datasetKey":"dataset_key"})
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

**Step 7: Subsetting**

1. Select only the preserved specimens from `prey`.

In [21]:
# Use .columns to see an index of column names and find the right column
prey.columns

# Use .value_counts() on the `basisOfRecords` column to locate PRESERVED_SPECIMEN
prey['basisOfRecord'].value_counts()

basisOfRecord
HUMAN_OBSERVATION      100284
PRESERVED_SPECIMEN      10482
MATERIAL_SAMPLE           389
MACHINE_OBSERVATION         1
Name: count, dtype: int64

In [23]:
prey[prey['basisOfRecord']=='PRESERVED_SPECIMEN']

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
1679,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,34.340000,-119.410004,2016-11-29T00:00:00Z,29.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1680,154.372528,200.300980,114.870407,475.911072,108.406372,0.000000,100.069076,290.060028,2.000000,6.201149,285.269562,129.936645,57.310860,3349.972412,272.703095,47.010059,225.693039,117.870407,194.108063,0.802846,139.021927,grassland,4859.104980
1680,Insecta,Hymenoptera,Xyelidae,Xyela,Xyela concava,38.759998,-119.660004,2016-06-25T00:00:00Z,25.0,6.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1681,79.070374,170.401947,-1.718157,452.265961,73.694450,12.075387,58.115467,199.897278,44.346771,44.346771,199.846512,160.934799,44.482346,6806.624023,281.522827,-74.999733,356.522553,6.357229,170.401947,NaN,1877.535400,savanna,3379.441650
1681,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,34.290001,-119.230003,2016-11-24T00:00:00Z,24.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1682,155.460648,198.497498,118.571289,430.013184,99.510902,0.000000,99.702957,259.023773,2.000000,5.190607,255.809418,131.268570,59.336895,3137.429199,269.109345,49.446285,219.663071,120.854431,191.976440,2.306774,154.871475,closed_shrubland,3700.706543
1682,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.689999,-117.180000,2016-11-25T00:00:00Z,25.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1683,171.975601,212.391007,136.951187,251.560730,54.389912,0.463668,90.511932,151.170273,3.463668,6.463668,132.243484,82.952835,49.488071,2921.583740,251.367142,84.462578,166.904572,139.487518,203.927338,0.592433,NaN,grassland,3317.774902
1683,Insecta,Hymenoptera,Xyelidae,Xyela,Xyela concava,38.660000,-119.589996,2016-06-25T00:00:00Z,25.0,6.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1684,55.478683,142.975632,-20.735058,588.114624,94.990501,14.623221,58.780247,260.451935,53.345188,53.345188,259.053162,150.054962,43.945538,6525.333984,245.996719,-90.450348,336.447052,-13.016450,142.975632,30.419949,2300.984619,savanna,3184.269775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

2. Select observations between 1992 and 2000.

In [36]:
# Do a value count of `year` to see what values we need
prey['year'].value_counts()

year
2022    19817
2020    19684
2021    18884
2019    17630
2018     7907
        ...
1990       55
2001       44
1986       43
1988       40
2000       31
Name: count, Length: 77, dtype: int64

In [37]:
# Use & to get values between 1992 and 2000
prey[(prey['year']>=1992) & (prey['year']<=2000)] 
prey['year'].value_counts()

year
2022    19817
2020    19684
2021    18884
2019    17630
2018     7907
        ...
1990       55
2001       44
1986       43
1988       40
2000       31
Name: count, Length: 77, dtype: int64

3. Select all rows for columns `species` and `eventDate`.

In [38]:
prey[['species', 'eventDate']]

                          species             eventDate
0             Sympetrum corruptum  2020-09-29T08:24:00Z
1           Armadillidium vulgare  2021-12-04T14:49:59Z
2             Bombus vosnesenskii  2021-06-18T08:52:00Z
3                  Apis mellifera  2016-04-17T09:28:00Z
4            Oncopeltus fasciatus  2019-04-06T18:44:31Z
...                           ...                   ...
111151  Pogonomyrmex californicus  1980-04-10T00:00:00Z
111152  Pogonomyrmex californicus  1998-03-26T00:00:00Z
111153     Liometopum occidentale  2010-05-21T00:00:00Z
111154  Pogonomyrmex californicus  2010-05-25T00:00:00Z
111155             Vanessa cardui  1992-09-02T00:00:00Z

[111156 rows x 2 columns]

4. Select observations that are greater than 37 degree latitude and less than 39 degree latitude.

In [39]:
prey.columns
prey['lat'].value_counts()
prey[(prey['lat']>37) & (prey['lat']<39)]

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
5,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,37.842187,-122.272478,2020-05-02T10:28:25Z,2.0,5.0,2020,iNaturalist,917.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,6,144.511795,178.412857,105.581818,565.076050,122.171043,1.000000,87.983589,308.378662,7.063087,9.205670,308.378662,89.164856,51.079494,2885.461670,234.265152,60.451580,173.813568,105.581818,172.760529,0.365533,35.971046,urban,3031.351807
9,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,37.323517,-122.174308,2019-04-29T15:22:16Z,29.0,4.0,2019,iNaturalist,5.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,10,131.805481,181.386352,89.509621,824.623535,164.044968,2.000000,86.375435,431.711121,11.555281,15.646415,431.711121,118.941368,54.445618,3672.007080,252.594223,35.436752,217.157471,89.509621,176.914505,1.444703,532.485596,evergreen_needleleaf,7056.129395
10,Insecta,Lepidoptera,Sphingidae,Hyles,Hyles lineata,38.412833,-121.421913,2020-03-27T07:12:56Z,27.0,3.0,2020,iNaturalist,65.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11,158.215454,229.449997,82.928772,436.710846,94.928772,1.000000,86.713325,231.857544,6.000000,10.000000,231.857544,142.071228,46.286674,5830.274902,334.665436,30.430893,304.234558,82.928772,229.215454,2.179459,8.622081,urban,3572.570801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111125,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.194660,-121.751556,2018-04-25T12:45:00Z,25.0,4.0,2018,iNaturalist,8.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,111126,149.664825,205.208023,94.005379,531.461853,111.061920,1.048737,89.384117,284.573364,5.116037,10.512528,284.573364,142.562775,52.976009,4377.099609,295.591431,29.022675,266.568756,94.005379,202.584701,3.201634,130.009628,cropland,4547.689453
111128,Malacostraca,Isopoda,Oniscidae,Oniscus,Oniscus asellus,37.559484,-122.456950,2022-01-13T10:13:41Z,13.0,1.0,2022,iNaturalist,28388.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,111129,127.518570,162.910614,96.093811,795.032043,156.520630,2.000000,85.520630,407.152374,11.976031,16.407465,404.746948,95.418083,57.000000,2662.222656,216.888702,50.028584,166.860123,101.551277,156.936645,4.066657,298.642273,mixed_forest,7247.124023
111138,Insecta,Diptera,Syrphidae,Toxomerus,Toxomerus marginatus,38.578009,-121.458785,2019-09-08T11:12:00Z,8.0,9.0,2019,iNaturalist,185.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,111139,160.217209,234.149902,84.482697,453.069031,98.832695,1.000000,87.000000,241.399902,6.000000,10.284519,241.399902,139.584610,44.782787,5925.384766,339.667206,33.198174,306.469025,84.482697,233.149902,0.625945,8.094406,urban,3895.930420
111140,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.337742,-121.714890,2022-09-05T10:38:00Z,5.0,9.0,2022,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,111141,143.193558,211.388290,83.208183,637.052978,126.192902,1.990560,85.568878,331.547668,8.638095,14.412238,331.547668,142.133209,49.171150,5099.305664,310.404297,24.262123,286.142181,83.208183,208.388290,1.101078,550.305786,grassland,5240.181152
111145,Insecta,Coleoptera,Coccinellidae,Hippodamia,Hippodamia convergens,37.065210,-119.136566,2022-07-24T12:09:35Z,24.0,7.0,2022,iNaturalist,28447.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,111146,81.055229,160.304352,18.500771,871.291321,161.897522,5.132826,79.517464,444.946442,21.579014,36.097893,438.846161,129.498886,44.000000,5771.552734,249.680740,-39.658085,289.338806,19.932720,158.954651,12.641203,1951.871948,evergreen_needleleaf,5783.545898